
import Database.Accounts;
import Database.Accounts_;
import java.awt.event.KeyEvent;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Rachel Ann Ligad
 */
public class Login extends java.awt.Frame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        subjectBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 77, 128), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("UltraCondensedSansSerif", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 77, 128));
        jLabel9.setText("Student Attendance System");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 370, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Doscst.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 80));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 80));

        jPanel2.setBackground(new java.awt.Color(0, 77, 128));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2), "Faculty Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, -40, 220, 260));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Number");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        idField.setBackground(new java.awt.Color(0, 77, 128));
        idField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idField.setForeground(new java.awt.Color(255, 255, 255));
        idField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subject");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        subjectBox.setBackground(new java.awt.Color(0, 77, 128));
        subjectBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subjectBox.setForeground(new java.awt.Color(255, 255, 255));
        subjectBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- SELECT SUBJECT -", "Object Oriented Programming", "Data Structure", "Platform Technologies", "Web Systems and Technology" }));
        subjectBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        subjectBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subjectBoxKeyPressed(evt);
            }
        });
        jPanel2.add(subjectBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 170, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login-xxl.png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, 40));

        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Faculty Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 370, 160));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 530, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void subjectBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subjectBoxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            submit();
        }
    }//GEN-LAST:event_subjectBoxKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        submit();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> subjectBox;
    // End of variables declaration//GEN-END:variables

    public void submit() {

        try {
            String sub = subjectBox.getSelectedItem().toString();
            String pass = new String(idField.getPassword());

            if (sub.isEmpty() || pass.isEmpty()) {
                JOptionPane.showMessageDialog(null, "FILL UP THE EMPTY FIELDS!", "ERROR!", JOptionPane.ERROR_MESSAGE);
            } else {

                EntityManagerFactory emf = Persistence.createEntityManagerFactory("StudentAttendanceSystemPU");
                EntityManager em = emf.createEntityManager();
                CriteriaBuilder cb = em.getCriteriaBuilder();
                CriteriaQuery<Accounts> cq = cb.createQuery(Accounts.class);
                Root<Accounts> root = cq.from(Accounts.class);

                cq.where(
                        cb.equal(root.get(Accounts_.subject), sub),
                        cb.equal(root.get(Accounts_.idNumber), pass)
                );

                TypedQuery<Accounts> q = em.createQuery(cq);
                Accounts account = q.getSingleResult();
                account.getSubject();
                account.getIdNumber();
                JOptionPane.showMessageDialog(null, "ACCESS GRANTED!\n" + account.getFacultyName(), "Student Attendance System",
                        JOptionPane.INFORMATION_MESSAGE);
                dispose();
                Enroll en = new Enroll();
                en.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ACCESS DENIED!", "WARNING!",
                    JOptionPane.WARNING_MESSAGE);
            idField.setText(null);
            subjectBox.setSelectedIndex(0);
            idField.requestFocus();
        }

    }
}
